export const paints = [
  {
    image: 'ProClassic.png',
    name: 'Краска интерьерная ProClassic',
    price: 4800,
    oldPrice: 5200,
    alt: 'Акриловая краска ProClassic белого цвета',
    categories: ['new', 'in-stock', 'exclusive'],
    stock: 15,
    rating: 4.8,
    createdAt: '2023-10-15'
  },
  {
    image: 'Duration Home Interior Acrylic.png',
    name: 'Краска Duration Home Interior',
    price: 5200,
    oldPrice: 5800,
    alt: 'Акриловая интерьерная краска Duration',
    categories: ['in-stock', 'contract'],
    stock: 8,
    rating: 4.0,
    createdAt: '2023-09-12'
  },
  {
    image: 'Emerald.png',
    name: 'Краска Emerald премиум',
    price: 6100,
    oldPrice: null,
    alt: 'Краска Emerald для внутренних работ',
    categories: ['new', 'exclusive'],
    stock: 5,
    rating: 3.9,
    createdAt: '2023-11-05'
  },
  {
    image: 'Latex Primer.png',
    name: 'Грунтовка Latex Primer',
    price: 3200,
    oldPrice: 3500,
    alt: 'Латексная грунтовка-праймер',
    categories: ['in-stock'],
    stock: 20,
    rating: 4.6,
    createdAt: '2023-07-18'
  },
  {
    image: 'ProClassic White.png',
    name: 'Краска ProClassic White',
    price: 4500,
    oldPrice: null,
    alt: 'Белая краска ProClassic матовая',
    categories: ['sale', 'in-stock'],
    stock: 12,
    rating: 4.5,
    createdAt: '2023-08-22'
  },
  {
    image: 'SuperPaint.png',
    name: 'Краска SuperPaint универсальная',
    price: 5500,
    oldPrice: 6000,
    alt: 'Универсальная краска SuperPaint',
    categories: ['new', 'in-stock'],
    stock: 7,
    rating: 4.7,
    createdAt: '2023-10-30'
  },
  {
    image: 'Surface Enamel.png',
    name: 'Эмаль Surface Enamel',
    price: 6800,
    oldPrice: null,
    alt: 'Глянцевая эмаль Surface для металла',
    categories: ['exclusive'],
    stock: 3,
    rating: 4.8,
    createdAt: '2023-11-15'
  },
  {
    image: 'Emerald.png',
    name: 'Краска Emerald для кухни',
    price: 5300,
    oldPrice: 5700,
    alt: 'Моющаяся краска Emerald для кухни',
    categories: ['in-stock'],
    stock: 10,
    rating: 4.3,
    createdAt: '2023-09-01'
  },
  {
    image: 'ProClassic.png',
    name: 'Краска ProClassic для потолков',
    price: 4200,
    oldPrice: null,
    alt: 'Потолочная краска ProClassic',
    categories: ['in-stock', 'contract'],
    stock: 18,
    rating: 4.4,
    createdAt: '2023-08-10'
  },
  {
    image: 'Duration Home Interior Acrylic.png',
    name: 'Краска Duration для ванной',
    price: 5800,
    oldPrice: null,
    alt: 'Влагостойкая краска Duration',
    categories: ['new', 'exclusive'],
    stock: 6,
    rating: 4.8,
    createdAt: '2023-11-01'
  },
  {
    image: 'ProClassic.png',
    name: 'Краска интерьерная ProClassic',
    price: 3450,
    oldPrice: 4200,
    alt: 'Акриловая краска ProClassic белого цвета',
    categories: ['sale', 'in-stock'],
    stock: 12,
    rating: 4.9,
    createdAt: '2023-11-16'
  },
  {
    image: 'Duration Home Interior Acrylic.png',
    name: 'Краска Duration Home Interior',
    price: 5200,
    oldPrice: 5800,
    alt: 'Акриловая интерьерная краска Duration',
    categories: ['new', 'in-stock', 'contract'],
    stock: 8,
    rating: 4.3,
    createdAt: '2023-09-12'
  },
  {
    image: 'Emerald.png',
    name: 'Краска Emerald премиум',
    price: 5100,
    oldPrice: null,
    alt: 'Краска Emerald для внутренних работ',
    categories: ['new', 'exclusive'],
    stock: 5,
    rating: 4.1,
    createdAt: '2023-11-05'
  },
  {
    image: 'Latex Primer.png',
    name: 'Грунтовка Latex Primer',
    price: 4200,
    oldPrice: 4500,
    alt: 'Латексная грунтовка-праймер',
    categories: ['in-stock', 'new', 'exclusive'],
    stock: 20,
    rating: 4.6,
    createdAt: '2023-07-18'
  },
  {
    image: 'ProClassic White.png',
    name: 'Краска ProClassic White',
    price: 4500,
    oldPrice: null,
    alt: 'Белая краска ProClassic матовая',
    categories: ['sale', 'in-stock', 'exclusive', 'contract'],
    stock: 12,
    rating: 4.5,
    createdAt: '2023-08-22'
  },
  {
    image: 'SuperPaint.png',
    name: 'Краска SuperPaint универсальная',
    price: 5500,
    oldPrice: 6000,
    alt: 'Универсальная краска SuperPaint',
    categories: ['new', 'in-stock'],
    stock: 7,
    rating: 4.2,
    createdAt: '2023-10-30'
  },
  {
    image: 'Surface Enamel.png',
    name: 'Эмаль Surface Enamel',
    price: 6800,
    oldPrice: null,
    alt: 'Глянцевая эмаль Surface для металла',
    categories: ['new','exclusive'],
    stock: 3,
    rating: 4.4,
    createdAt: '2023-11-15'
  },
  {
    image: 'Emerald.png',
    name: 'Краска Emerald для кухни',
    price: 5350,
    oldPrice: 5600,
    alt: 'Моющаяся краска Emerald для кухни',
    categories: ['in-stock','contract'],
    stock: 10,
    rating: 4.6,
    createdAt: '2023-09-01'
  },
  {
    image: 'ProClassic.png',
    name: 'Краска ProClassic для потолков',
    price: 4270,
    oldPrice: null,
    alt: 'Потолочная краска ProClassic',
    categories: ['new', 'in-stock', 'contract'],
    stock: 18,
    rating: 4.4,
    createdAt: '2023-08-10'
  },
  {
    image: 'Duration Home Interior Acrylic.png',
    name: 'Краска Duration для ванной',
    price: 3820,
    oldPrice: null,
    alt: 'Влагостойкая краска Duration',
    categories: ['new', 'exclusive', 'contract'],
    stock: 6,
    rating: 4.8,
    createdAt: '2023-11-01'
  },
  {
    image: 'Surface Enamel.png',
    name: 'Эмаль Surface для радиаторов',
    price: 7200,
    oldPrice: 8000,
    alt: 'Термостойкая эмаль для радиаторов',
    categories: ['sale', 'exclusive'],
    stock: 4,
    rating: 4.9,
    createdAt: '2023-11-20'
  }
];